export { default as Downloads } from './Downloads';
export { default as HomePage } from './HomePage';
export { default as Policies } from './Policies';
export { default as PrivacyPolicy } from './PrivacyPolicy';
export { default as Disclaimer } from './Disclaimer';
export { default as InvestorCharter } from './InvestorCharter';
export { default as Pricing } from './Pricing';
export { default as ContactUs } from './ContactUs';
export { default as AboutUsPage } from './AboutUsPage';